name: GitHub App Authentication
description: 'GitHub App - Authenticate as an Installation'
author: vedantmgoyal2009
inputs:
  app-id:
    description: 'GitHub App ID'
    required: true
  private-key:
    description: 'GitHub App Private Key'
    required: true
  client-id:
    description: 'GitHub App Client ID'
    required: true
  client-secret:
    description: 'GitHub App Client Secret'
    required: true
  installation-id:
    description: 'GitHub App Installation ID'
    required: true
outputs:
  auth-token:
    description: 'GitHub App Authentication Token'
    value: ${{ steps.authenticate.outputs.token }}
runs:
  using: composite
  steps:
    - name: Authenticate and get token
      run: |
        npm install @octokit/auth-app
        echo 'async function main() {
          console.log((await require("@octokit/auth-app").createAppAuth({
            appId: ${{ inputs.app-id }},
            privateKey: "${{ inputs.private-key }}",
            clientId: "${{ inputs.client-id }}",
            clientSecret: "${{ inputs.app-id }}",
            installationId: ${{ inputs.installation-id }},
          })({ type: "installation" })).token);
        }
        main();' > auth.js
        echo "::set-output name=token::$(node auth.js)"
      shell: bash
      id: authenticate
