documentation:
- 'README.md'
new package:
- 'packages/**'
custom_scripts:
- 'custom_scripts/**'
automation-core:
- 'automation.ps1'
- 'YamlCreate/YamlCreate.ps1'
- '.github/**'
add-contributor:
- 'README.md'
- '.all-contributorsrc'
