documentation:
- all: ['README.md']
new package:
- 'packages/**'
package-scripts:
- 'package_scripts/**'
automation-core:
- 'scripts/**'
- '.github/**'
add-contributor:
- all: ['README.md','.all-contributorsrc']
