# Any markdown file can be considered part of documentation
documentation:
- any: ['*.md','**/*.md']
packages:
- packages/**/*.json
custom_scripts:
- custom_scripts/**/*.ps1
automation-core:
- automation.ps1
- YamlCreate/YamlCreate.ps1
- .github/**/*.yml
add-contributor:
- all: ['README.md','.all-contributorsrc']
