version = 1

exclude_patterns = [
  "website/assets/**",
  "CODE_OF_CONDUCT.md",
  "LICENSE",
  "package-lock.json",
  "tsconfig.json",
  "vercel.json"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/vedantmgoyal9/vedantmgoyal9/sheltasks-cli"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "prettier"

[[transformers]]
name = "ruff"