name: Automation
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run automation script
        shell: pwsh
        run: Set-Location .\scripts; .\Automation.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.MYSUPERSECRETINFORMATION }}
          JWT_RB: ${{ secrets.JWT_RB }}
          MS_ID: ${{ secrets.MS_ID }}
          THIS_ID: ${{ secrets.THIS_ID }}
