name: CI
run-name: ${{ inputs.what-to-run }}

on:
  workflow_dispatch:
    inputs:
      what-to-run:
        description: What to run?
        type: choice
        options:
          - Add package versions (Json input)
          - Move packages (Json input)
        default: 'WinGet Automation'
        required: true
      json-input:
        description: Json input
        type: string
        default: '[ ]'
        required: true

jobs:
  wpa-automation:
    name: WinGet Automation
    runs-on: windows-latest
    steps:
      - name: Checkout repository 👋
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Run automation script 🤖
        run: |
          If ('Add package versions (Json input)' -eq '${{ inputs.what-to-run }}') {
            .\Add-PackageVersions.ps1 -JsonInput '${{ inputs.json-input }}'
          } ElseIf ('Move packages (Json input)' -eq '${{ inputs.what-to-run }}') {
            .\Move-Packages.ps1 -JsonInput '${{ inputs.json-input }}'
          }
        env:
          GITHUB_TOKEN: ${{ secrets.MYSUPERSECRETINFORMATION }}
        shell: pwsh
