name: CI
run-name: ${{ github.event.head_commit.message || inputs.what-to-run || 'WinGet Automation' }}
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      what-to-run:
        description: What to run?
        type: choice
        options:
          - WinGet Automation
          - Add package versions (Json input)
          - Move packages (Json input)
        default: 'WinGet Automation'
        required: true
      json-input:
        description: Json input
        type: string
        default: '[ ]'
        required: true
jobs:
  wpa-automation:
    name: WinGet Automation
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: winget-pkgs-automation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Run automation script
        run: |
          If ($env:GITHUB_EVENT_NAME -eq 'schedule' -or  'WinGet Automation' -eq '${{ inputs.what-to-run }}') {
            .\Automation.ps1
          } ElseIf ('Add package versions (Json input)' -eq '${{ inputs.what-to-run }}') {
            .\Add-PackageVersions.ps1 -JsonInput '${{ inputs.json-input }}'
          } ElseIf ('Move packages (Json input)' -eq '${{ inputs.what-to-run }}') {
            .\Move-Packages.ps1 -JsonInput '${{ inputs.json-input }}'
          }
        env:
          AP_ID: ${{ secrets.BT_AP_ID }}
          AP_PKY: ${{ secrets.BT_AP_PKY }}
          INST_ID: ${{ secrets.BT_INST_ID }}
          GITHUB_TOKEN: ${{ secrets.MYSUPERSECRETINFORMATION }}
  codeql-analysis:
    name: CodeQL (analyse)
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
        # language: [ 'java', 'javascript' ] <-- auto-detected, commented manually
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see https://github.com/github/codeql-action)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
