name: Fetch Old Versions
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5
      - name: Run fetch-old-versions.ps1
        shell: pwsh
        run: ./scripts/FetchOldVersions.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.MYSUPERSECRETINFORMATION }}
