name: Update WinGetDev

on:
  schedule:
    - cron: 30 5,17 * * *
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout microsoft/winget-cli 👋
        uses: actions/checkout@v4
        with:
          repository: microsoft/winget-cli
          persist-credentials: false

      - name: Build winget-cli 🛠️
        run: |
          New-Item -Name .\wingetdev-build\ -ItemType Directory
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat' x64
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe' -t:restore -m -p:RestorePackagesConfig=true -p:Configuration=Release -p:Platform=x64 .\src\AppInstallerCLI.sln
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe' -m -p:Configuration=Release -p:Platform=x64 .\src\AppInstallerCLI.sln
          Copy-Item -Path .\src\x64\Release\WindowsPackageManager\WindowsPackageManager.dll -Destination .\wingetdev-build\WindowsPackageManager.dll -Force
          Move-Item -Path .\src\x64\Release\AppInstallerCLI\* -Destination .\wingetdev-build\ -Force
          Rename-Item -Path .\wingetdev-build\winget.exe -NewName .\wingetdev.exe
        shell: pwsh

      - name: Update release 🚀
        uses: softprops/action-gh-release@v2
        with:
          name: 🪟WinGet Nightly Builds (wingetdev)📦🛠️
          tag_name: wingetdev/nightly
          draft: false
          prerelease: true
          files: wingetdev-build/*
          fail_on_unmatched_files: true
          append_body: false
          generate_release_notes: false
          token: ${{ secrets.GITHUB_TOKEN }}
