name: 'WinGet Automation'
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
# Doesn't work well with the automation
# concurrency:
#   group: ${{ github.workflow }}
#   cancel-in-progress: false # true
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: src/winget-pkgs-automation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Authenticate GitHub Bot
        run: |
          # Initialize auth.js which will be used by the script to get bot token
          npm ci
          Write-Output '(async () => {
            console.log((await require("@octokit/auth-app").createAppAuth({
              appId: ${{ secrets.BT_AP_ID }},
              privateKey: "${{ secrets.BT_AP_PKY }}",
              installationId: ${{ secrets.BT_INST_ID }},
            })({ type: "installation" })).token);
          })();' | Out-File -FilePath auth.js
      - name: Run automation script
        run: .\Automation.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.MYSUPERSECRETINFORMATION }}
