name: "[WPA] Pre-validation"
on:
  push:
    branches: [main]
    paths:
      - 'winget-pkgs-automation/**'
  pull_request:
    branches: [main]
    paths:
      - 'winget-pkgs-automation/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        working-directory: winget-pkgs-automation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: npm install @commitlint/config-conventional
      - if: github.event_name == 'push'
        name: Validate Commit (push)
        shell: bash
        run: git log -1 --pretty=format:"%s" | npx commitlint --verbose
      - if: github.event_name == 'pull_request'
        name: Validate Commits (pull request)
        shell: bash
        run:  npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - if: github.event_name == 'push'
        name: Update packages.txt
        run: |
          Invoke-Pester -Output Detailed
          git config --local user.name 'winget-pkgs-automation-bot[bot]'
          git config --local user.email '93540089+winget-pkgs-automation-bot[bot]@users.noreply.github.com'
          git commit -m "chore: update packages.txt" -- ../packages.txt
          git push https://x-access-token:$((Invoke-RestMethod -Method Post -Headers @{Authorization = "Bearer $($env:JWT_RB | ruby)"; Accept = "application/vnd.github.v3+json"} -Uri "https://api.github.com/app/installations/$env:THIS_ID/access_tokens").token)@github.com/vedantmgoyal2009/winget-pkgs-automation.git
        env:
          JWT_RB: ${{ secrets.JWT_RB }}
          THIS_ID: ${{ secrets.THIS_ID }}
      - uses: codecov/codecov-action@v2
        with:
          name: winget-pkgs-automation-codecov
          directory: ./
          files: ./coverage.xml
          working-directory: winget-pkgs-automation/scripts
          fail_ci_if_error: false
          verbose: true
