name: '[WPA] Automation'
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: src/winget-pkgs-automation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Clone microsoft/winget-pkgs
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: src/winget-pkgs-automation/winget-pkgs
          persist-credentials: false
          repository: microsoft/winget-pkgs
      - name: Authenticate GitHub Bot
        run: |
          # Initialize auth.js which will be used by the script to get bot token
          npm ci
          Write-Output 'async function main() {
            console.log((await require("@octokit/auth-app").createAppAuth({
              appId: ${{ secrets.BT_AP_ID }},
              privateKey: "${{ secrets.BT_AP_PKY }}",
              clientId: "${{ secrets.BT_CLNT_ID }}",
              clientSecret: "${{ secrets.BT_CLNT_SCRT }}",
              installationId: ${{ secrets.BT_INST_ID }},
            })({ type: "installation" })).token);
          }
          main();' | Out-File -FilePath auth.js
      - name: Run automation script
        run: .\Automation.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.MYSUPERSECRETINFORMATION }}
